name: Update README from other repositories

on:
  push:
    branches:
      - main
  repository_dispatch:
  schedule:
    - cron: '0 * * * *'  # Exécute toutes les heures

jobs:
  update-readme:
    runs-on: ubuntu-latest
    container:
      image: php:8.3-cli
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install dependencies
        run: |
          apt-get update && apt-get install -y git curl jq
      - name: Test PHP
        run: php -v
      - name: Run PHP script
        run: php ../scripts/test.php
