name: Update README from other repositories

on:
  push:
    branches:
      - main
  repository_dispatch:
  # schedule:
  #   - cron: '0 * * * *'  # Exécute toutes les heures

jobs:
  update-readme:
    runs-on: ubuntu-latest
    container:
      image: php:8.3-cli
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install dependencies
        run: |
          apt-get update && apt-get install -y git curl jq
      - name: Test PHP
        run: php -v
      - name: Run PHP script
        run: |
          curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
          cd .github/scripts && composer install
          php .github/scripts/update-readme.php --token=${{ secrets.ACTION_TOKEN }}
      - name: Configure Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
      - name: Commit and push changes
        run: |
          git add README.md
          git commit -m "Auto-update README [skip ci]" || echo "No changes to commit"
          git push origin main
